#!/usr/bin/env ansible-playbook
---
# ansible to download osmo-iuh sources and compile them.
# This is based on information from http://osmocom.org/news/59
# so uses sources from September 2016

# expects a freshly installed jessie system with:
## iuh user in sudo group
## sudo installed

- hosts: 172.16.176.134
#- hosts: 172.16.176.137
  remote_user: iuh
  become_method: sudo


  vars:
    osmo_checkout_base:      "/home/iuh/_code/"
    omso_config_base:        "/home/iuh/3G-config/"
    hnb_adapter_ip:          

  roles:
  - iuh-sep16
  - osmo-iuh-config-sep16
